name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java-version:
          - 11
          - 17
          - 18
        jdk-dist:
          - adopt-hotspot
          - temurin
    runs-on: ${{ matrix.os }}
    name: Run tests via ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}, on ${{ matrix.os }}
    steps:
      - name: Set ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: sbt test

  test-release:
    name: Test Release
    needs:
      - check
    runs-on: ubuntu-latest
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    concurrency:
      group: test-release-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: '17'
      - name: Sbt check publish artifacts
        run: sbt +publishLocal

  success:
    runs-on: ubuntu-latest
    needs:
      - check
      - test-release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}